[azure]
AZURE_OPENAI_ENDPOINT="https://polite-ground-030dc3103.4.azurestaticapps.net/api/v1"
AZURE_OPENAI_KEY="5df7f9f9-aaed-467f-9edb-cd7ca2a6c757"
AZURE_OPENAI_API_VERSION="2024-02-01"

[newsapi]
API_KEY = '6edb681fd9db484f808a3ad60d7cc32d'